version: '3'  # Specifies the version of the Docker Compose file format

services:  # Defines the services that make up your application

  db:  # This service is for the MariaDB database
    image: mariadb  # Uses the official MariaDB image from Docker Hub
    env_file:  # Specifies the file from which to read environment variables
      - .env
    volumes:  # Mounts paths on the host machine to paths in the container
      - db_data:/var/lib/mysql  # Persists the database data in a volume
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initializes the database with an SQL script

  node-service:  # This service is for the Node.js application
    build: ./api  # Specifies the directory where the Dockerfile for this service is located, which Docker Compose will use to build the image
    env_file:  # Uses the same .env file to set environment variables for this service
      - .env
    depends_on:  # Specifies that this service depends on the db service, ensuring the database is ready before the node-service starts
      - db

  nginx:  # This service is for the Nginx web server
    build: ./nginx  # Points to the directory containing the Dockerfile to build the Nginx image
    ports:  # Maps port 8080 on the host to port 80 in the container, making the Nginx server accessible from the host
      - "8080:80"
    volumes:  # Mounts the custom nginx configuration into the container
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:  # Specifies that nginx should start after node-service is available
      - node-service

volumes:  # Declares named volumes that can be used by the services
  db_data:  # Named volume for persisting database data
